name: emer
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - openblas  # Use OpenBLAS instead of MKL for ARM compatibility
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-python=1.0.9
  - ca-certificates
  - certifi
  - click
  - colorama
  - comm
  - contourpy
  - cycler
  - dbus
  - debugpy
  - decorator
  - docker-pycreds
  - et_xmlfile
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - filelock
  - fontconfig
  - fonttools
  - freetype
  - gitdb
  - gitpython
  - glib
  - gmp
  - gmpy2
  - gnutls
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - lame
  - lcms2
  - lerc
  - libclang
  - libiconv
  - libjpeg-turbo
  - libxml2
  - matplotlib
  - matplotlib-inline
  - mpfr
  - mpmath
  - munkres
  - ncurses
  - nettle
  - networkx
  - numexpr
  - numpy-base
  - openpyxl
  - openssl
  - packaging
  - parso
  - pathtools
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - plotly
  - prompt-toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - pyqt5-sip
  - python=3.11
  - pytorch
  - pytorch-mutex=1.0
  - pytz
  - pyyaml
  - pyzmq
  - requests
  - scikit-learn
  - sentry-sdk
  - setuptools
  - six
  - smmap
  - sqlite
  - stack_data
  - sympy
  - tbb
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - tzdata
  - wandb
  - wcwidth
  - wheel
  - xz
  - yaml
  - zipp
  - zlib
  - zstd
  - pip:
      - aiohttp
      - aiosignal
      - allensdk
      - argschema
      - attrs
      - blosc2
      - boto3
      - botocore
      - cachetools
      - distro
      - edfio
      - eeglabio
      - frozenlist
      - future
      - glymur
      - greenlet
      - h5py
      - hdmf
      - imageio
      - jmespath
      - jsonschema
      - jsonschema-specifications
      - lazy-loader
      - lxml
      - marshmallow
      - mne
      - msgpack
      - multidict
      - ndindex
      - ndx-events
      - nptyping
      - numpy
      - pandas
      - patsy
      - pooch
      - psycopg2-binary
      - py-cpuinfo
      - pynrrd
      - pynwb
      - referencing
      - requests-toolbelt
      - rpds-py
      - ruamel-yaml
      - s3transfer
      - scikit-build
      - scikit-image
      - scipy
      - seaborn
      - semver
      - simpleitk
      - simplejson
      - sqlalchemy
      - statsmodels
      - tables
      - tifffile
      - urllib3
      - xarray
      - yarl